services:
  - type: web
    name: amulet-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3